# TEXT MINING for PRACTICE: Numpy
---

In [1]:
import numpy as np

## 1. 배열 (Array) 생성

### 1-1. List를 Array로

In [3]:
list_1 = [1,2,3,4]
list_2 = ['a','b','c','d','e']
list_3 = [[1,2,3],[4,5,6],[7,8,9]]
print(list_1)
print(list_2)
print(list_3)

[1, 2, 3, 4]
['a', 'b', 'c', 'd', 'e']
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = np.array(list_3)
print(array_1)
print(array_2)
print(array_3)

[1 2 3 4]
['a' 'b' 'c' 'd' 'e']
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 1-2. Arange 소개

In [ ]:
range_list = list(range(5))
range_array = np.arange(5)
print(range_list)
print(range_array)

In [ ]:
range_array = np.arange(0,10,2)
print(range_array)

### 1-3. Linspace

In [6]:
np.linspace(0,10,7)


array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [7]:
np.linspace(0,100,60)


array([  0.        ,   1.69491525,   3.38983051,   5.08474576,
         6.77966102,   8.47457627,  10.16949153,  11.86440678,
        13.55932203,  15.25423729,  16.94915254,  18.6440678 ,
        20.33898305,  22.03389831,  23.72881356,  25.42372881,
        27.11864407,  28.81355932,  30.50847458,  32.20338983,
        33.89830508,  35.59322034,  37.28813559,  38.98305085,
        40.6779661 ,  42.37288136,  44.06779661,  45.76271186,
        47.45762712,  49.15254237,  50.84745763,  52.54237288,
        54.23728814,  55.93220339,  57.62711864,  59.3220339 ,
        61.01694915,  62.71186441,  64.40677966,  66.10169492,
        67.79661017,  69.49152542,  71.18644068,  72.88135593,
        74.57627119,  76.27118644,  77.96610169,  79.66101695,
        81.3559322 ,  83.05084746,  84.74576271,  86.44067797,
        88.13559322,  89.83050847,  91.52542373,  93.22033898,
        94.91525424,  96.61016949,  98.30508475, 100.        ])

### 1-4. Ones! Zeros! Eye!

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 1-5. 난수 배열

In [13]:
np.random.rand(5)

array([0.75027283, 0.55522421, 0.88810373, 0.99595413, 0.83231515])

In [14]:
np.random.rand(3,3)

array([[0.38289827, 0.38413456, 0.88807459],
       [0.90078193, 0.01910411, 0.04085852],
       [0.22027284, 0.03436858, 0.10745639]])

In [15]:
np.random.randint(1,10,5)

array([1, 6, 1, 6, 3])

In [16]:
norm_d = np.random.randn(100)
norm_d.sort()
print(norm_d)

[-2.19469948 -1.66012305 -1.59970711 -1.38707541 -1.37015371 -1.36270833
 -1.3583013  -1.33375016 -1.15133825 -1.14138573 -1.11812706 -1.0872977
 -1.08484717 -1.06589922 -1.02205433 -0.95171941 -0.89093235 -0.87987761
 -0.87647479 -0.79543296 -0.77917692 -0.77307152 -0.75541522 -0.69045404
 -0.60739149 -0.57258307 -0.56356731 -0.54797219 -0.53740267 -0.53242389
 -0.53145364 -0.48671467 -0.47672896 -0.45781695 -0.42493006 -0.38918951
 -0.36749264 -0.32150766 -0.29649393 -0.2822429  -0.25691444 -0.2264772
 -0.22249174 -0.21173868 -0.15997202 -0.14419127 -0.12975024 -0.1151058
 -0.05133902 -0.04732333 -0.00631846  0.00396278  0.029158    0.05119598
  0.06551981  0.09169649  0.11938783  0.1335768   0.14914324  0.15030883
  0.15708455  0.1606315   0.2211075   0.22604714  0.30749449  0.33095069
  0.34757212  0.39269824  0.39291822  0.43870899  0.44364152  0.44879696
  0.47087263  0.49412218  0.57342195  0.60132772  0.61622416  0.72700206
  0.76031971  0.76108527  0.7617245   0.79287071  0.80

### 1-6. min, max, sum, mean, argmin, argmax

In [17]:
sample_matrix = np.random.randint(1,10,5)
print(sample_matrix)

[5 7 2 6 5]


In [18]:
sample_matrix.max()

7

In [19]:
sample_matrix.min()

2

In [20]:
sample_matrix.sum()

25

In [21]:
sample_matrix.mean()

5.0

In [22]:
sample_matrix.argmin()

2

In [23]:
sample_matrix.argmax()

1

### 1-7. Shape, Reshape

In [25]:
sample_matrix = np.random.randint(1,10,9)
print(sample_matrix)
print(sample_matrix.shape)

[1 9 6 2 3 8 3 2 6]
(9,)


In [26]:
sample_matrix = sample_matrix.reshape(3,3)
print(sample_matrix)

[[1 9 6]
 [2 3 8]
 [3 2 6]]


In [27]:
sample_matrix.shape

(3, 3)

## 2. 원소 접근

### 2-1. 기본 접근법

In [28]:
sample_array = np.random.randint(1,10,9)
print(sample_array)

[4 7 7 5 5 7 9 7 2]


In [29]:
sample_array[3]


5

In [30]:
sample_array[-1]

2

In [31]:
sample_array[1:3]

array([7, 7])

In [32]:
sample_array[1:]

array([7, 7, 5, 5, 7, 9, 7, 2])

In [33]:
sample_array[:-3]

array([4, 7, 7, 5, 5, 7])

In [34]:
sample_array[-3:]

array([9, 7, 2])

### 2-2. 원소할당

In [35]:
sample_array = np.random.randint(1,10,9)


In [36]:
sample_array[0:5] = -50
print(sample_array)

[-50 -50 -50 -50 -50   6   5   7   5]


In [37]:
sample_array[:] = 100
print(sample_array)

[100 100 100 100 100 100 100 100 100]


In [38]:
sample_array[:] += 100
print(sample_array)

[200 200 200 200 200 200 200 200 200]


In [39]:
sample_array[:] *= 3
print(sample_array)

[600 600 600 600 600 600 600 600 600]


### 2-3. 차원 (축) 선택

In [40]:
sample_matrix = np.random.randint(1,10,16).reshape(4,4)
print(sample_matrix)

[[3 7 9 2]
 [1 7 2 1]
 [3 2 7 9]
 [4 4 6 1]]


In [41]:
sample_matrix[0]


array([3, 7, 9, 2])

In [42]:
sample_matrix[-1]

array([4, 4, 6, 1])

In [43]:
sample_matrix[0:3]

array([[3, 7, 9, 2],
       [1, 7, 2, 1],
       [3, 2, 7, 9]])

In [44]:
sample_matrix[0][1]

7

In [45]:
sample_matrix[0,1]

7

In [46]:
sample_matrix[:,0]

array([3, 1, 3, 4])

In [47]:
sample_matrix[:,:1]

array([[3],
       [1],
       [3],
       [4]])

In [48]:
sample_matrix[:2,2:]


array([[9, 2],
       [2, 1]])

In [49]:
sample_matrix[[1,3]]

array([[1, 7, 2, 1],
       [4, 4, 6, 1]])

### 2-4. 조건부 선택

In [50]:
[sample_matrix>5]

[array([[False,  True,  True, False],
        [False,  True, False, False],
        [False, False,  True,  True],
        [False, False,  True, False]])]

In [51]:
sample_matrix[sample_matrix>5]

array([7, 9, 7, 7, 9, 6])

## 3. 배열/행열 연산

In [52]:
m = np.arange(1,10).reshape((3,3))
a = np.ones((3,3))
print(m)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3-1. 기본 연산

In [53]:
m+a

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [54]:
m-a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [55]:
m*a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
np.dot(m,a)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [57]:
a/m

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

### 3-2. 고급 연산
연산 관련 더 많은 함수들은 [여기](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)서 찾을 수 있습니다.

In [58]:
m = np.arange(1,10).reshape((3,3))*-1
a = np.ones((3,3)) * 2
print(m)
print(a)

[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [59]:
m = np.fabs(m)
print(m)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [60]:
np.log(m)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [61]:
np.exp(m)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [62]:
np.sin(m)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [63]:
np.lcm(m.astype(int),3)

array([[ 3,  6,  3],
       [12, 15,  6],
       [21, 24,  9]])

In [64]:
np.gcd(m.astype(int),3)

array([[1, 1, 3],
       [1, 1, 3],
       [1, 1, 3]])

In [65]:
np.greater(m,a)

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])